### ISSUE TITLE
MyQ Lite is no longer able to login to MyQ.com

### ISSUE THREAD

**Issue by phaldor8** [brbeaird/SmartThings_MyQ#70]
I had everything setup and working through Smartthings>IFTTT>Google Assistant/Alexa, but today I went to open my front gate and it didn't work.  In troubleshooting, I did notice an update to the MyQ SmartApp, so updated it, when I did that, my dummy sensor failed to keep the status of the gate as closed, now the door status is stuck in "unknown" or "opening."  So I tried to recreate the device handler and device, but in the Classic SmartThings app the MyQ failed on login.  It states that "The username or password you entered is incorrect.  Go back and try again."  Yet, the login works on both MyQ.com and myliftmaster.com.

**Comment by chriseverhart** [comment]
I have the same thing. I think chamberland just started pushing "myQ® Premium Services" free to download and will not open your garage door with verbal commands. I hope they didn't Fix the glitch.

**Comment by brbeaird** [comment]
Yes, MyQ made some changes today that effective broke our link the MyQ's v4 endpoint.

The good news is, it looks like the V5 endpoint is available, so I'm making changes right now to get it working again. Will push out an update hopefully later today.

**Comment by adrian97c** [comment]
Last week when I opened my Crafsfman app, it made me force merge into a myQ app on iOS.. it said they retired the craftsman app... then I realized the issue with MyQlite... but once I changed the setting to “liftmaster” then myqlite worked again.


________________________________

**Comment by phaldor8** [comment]
I was afraid of this happening as they are rather adamant about the
security ramifications.  I get it that if Alexa heard someone yell to open
the front door, that would cause some concern, but my gate is about 50
yards from the nearest voice activation point, so I'd like the ability
rather than have someone decide for me whether it's a risk or not.


Christopher Goodrich B.S., CISSP, ISSEP, ISSMP, HCISPP
phaldor8@gmail.com
phaldor@comcast.net
505-227-6130

**Comment by brbeaird** [comment]
I have a fixed version running on my end. Working out a few bugs, but I should have an update later tonight.

**Comment by phaldor8** [comment]
Due, you are AWESOME!!  Thank you so much, my dad will be happy again.


Christopher Goodrich B.S., CISSP, ISSEP, ISSMP, HCISPP
phaldor8@gmail.com
phaldor@comcast.net
505-227-6130

**Comment by phaldor8** [comment]
If you look on the myliftmaster.com page, it says roughly the same thing,
that the website is being sunsetted in favor of the mobile app, so I doubt
the Liftmaster trick will work for long.

Christopher Goodrich B.S., CISSP, ISSEP, ISSMP, HCISPP
phaldor8@gmail.com
phaldor@comcast.net
505-227-6130

**Comment by brbeaird** [comment]
Version update is out. SmartApp and both door device handlers have been changed. 

This is a VERY significant change and may still be a bit buggy, but it should work for most people. I'm sure we'll find stuff to fix over the next few weeks.

A couple important notes here:

1. After you update the code, you will need to open the MyQ Lite SmartApp config in the SmartThings Classic mobile app and tap on "Modify Devices." Tap all the way through selecting your devices and hit save. This is a very important step as we need to update the door ID's with the new ID's in MyQ.
2. Lamp module control is not currently working. I can't figure out what the new on/off command is, but hopefully someone will reverse-engineer for me at some point, and I'll update this code.

The biggest change behind the scenes is that with V5, MyQ has changed the door ID to be the door's serial number. I knew this day was coming, so with my previous update, I did my best to prepare the app to be able to automatically detect the change based on door name and simply update your existing devices. However, there's a chance the app ends up creating additional doors instead. If that happens, the easiest thing to do is to try and get your door names to match what they are in MyQ. If you still can't match them up, you may have better luck fully removing/re-setting up the SmartApp.

Let me know how it goes.

**Comment by adrian97c** [comment]
Updated app & handler, so far it worked fine including Alexa. I have a craftsman brand opener (had to select Liftmaster ever since the OEM craftsman app merged into MyQ login last week).

Thx for the updates.


________________________________

**Comment by jewalla** [comment]
Updated, works great. Thanks for all of your help!

**Comment by phaldor8** [comment]
Well, I got myself into a pickle....in my troubleshooting earlier, I had
deleted all handlers and devices, so I had to recreate them. Once I figured
out they worked (even though the status sticks in "Opening" it still
works), I asked Alexa and Google to use the pre-created triggers I had
through IFTTT.  They failed to open the gate.  I had to delete those and
re-create them as well, but now, as of this writing, I have two Alexa
triggers and one google trigger that work.  I don't pretend to know more
than this, I'm just glad I got it functional again.

Kudos to a quick reply and fix to Brian!!!  The rest is obviously on me.

Christopher Goodrich B.S., CISSP, ISSEP, ISSMP, HCISPP
phaldor8@gmail.com
phaldor@comcast.net
505-227-6130

**Comment by atlflyer** [comment]
What a nice world we live in. By the time I had noticed my garage door automations weren't working expected and I found my way here, there was already an issue posted and a comment from the author and Internet hero, brbeaird, that he was spending his time to fix it. Once the patch was out, it didn't work right away (my error, I'm sure). Posting my journey just in case it helps someone else.

I updated the code for the handlers and smartapp. I didn't have this project connected via github prior to today, so I don't know how out of date my previous version was. Following the step of "modify devices" gave me an error that the device already existed and that device still didn't work. Deleted the device, then went into the smart app and chose the "delete everything" (?don't quite remember for sure?) choice at the bottom. Then, went through the IDE for device handlers and smart app and deleted them there as well. Once that was all done, basically followed the steps in the readme to install the handlers and smart app from the github repository as if it were the first time. Added the smartapp from the my apps section, entered the login in credentials, and it all fell in to place from there. Of course, had to redo connecting that device to other smart apps, etc, since it had all been deleted.

Thanks, again, brbeaird. I saw your tip jar at the bottom of the readme. Going to donate and hope others who benefit do as well.

**Comment by phaldor8** [comment]
I want to mention one other bit of funky business here that I'm not sure
what happened.  One of the times that I was deleting/recreating the
simulated trigger and gate opener in SmartThings, I swear I was using the
Classic app, and when I ran it, I got an error on my phone from the NEW
app!  I checked it, and sure enough, the devices were showing there as well
for some odd reason.  Blowing them out again and putting them back
correctly got rid of the error, but the Simulated Gate Sensor I built to
handle the sensor for the MyQ Lite did appear back in the new SmartThings
app.

Given that I have a working solution, I'm not gonna touch it to even
attempt to figure it out.  My coding skills are so rusty they'll give you
tetanus, my hat is still off to Brian on this one.  Yes, I second the
comment about donating, his response was phenomenal.

Christopher Goodrich B.S., CISSP, ISSEP, ISSMP, HCISPP
phaldor8@gmail.com
phaldor@comcast.net
505-227-6130

**Comment by kc6108** [comment]
It’s still not working for me. I am noticing that when using the lock functionality the app doesn’t populate the garage door serial number during setup as it does when not selecting lock.

**Comment by richlawson** [comment]
Following the first instruction in https://github.com/brbeaird/SmartThings_MyQ/issues/70#issuecomment-544060143 worked for me - thank you for fixing this so quickly!

**Comment by brbeaird** [comment]
You’re correct - I have not fixed it for the lock device yet. Honestly
didn’t think people were still using that one.

**Comment by kc6108** [comment]
We don’t use Alexa. The lock functionality is the only way to ensure no one can open our garage door using Google/Nest devices.

**Comment by brbeaird** [comment]
I pushed out an update today to include the lock door handler. See if that
works for you.

**Comment by kc6108** [comment]
It’s working. Thanks!

**Comment by chriseverhart** [comment]
I don't know if I'm screwing up or if my door is being difficult.  I'm getting a "Gateway Brand: null" under my username and "Missing MyQ ID" under the connected devices. I'm also getting a notification that DoorDevice 3.1.0 is available and I have no idea how to update that.

**Comment by chriseverhart** [comment]
AND I feel dumb. update the device handlers Chris. I had to install All the parts

**Comment by fkenisky** [comment]
I get these emails all the time.  I started getting them when I installed the MyQ garage door opening system.  That's fine, I think what I'm seeing here is pretty interesting however, I've not yet had a problem with the code I downloaded about a year ore so ago.  It's worked fine for me.

I'm not exactly sure maybe because I don't have the problem, what all this is about and weather or not I need to do an upgrade, my feeling is that I shouldn't if it's working and I don't want to screw up anything as long as it is working.

So if someone could easily explain what is going on with the code, what problems did it cause and if the system can be updated automatically via one of the smart system (i.e. Alexa) that I've got it running on?

When I see posts here about the update I'm assuming since there is no other explanation that the update is a manual update that has to be performed on all smart home systems.  (i.e. Alexa, smartthings, MyQ)?  I noticed the one example of how to update using smartthings but what about the other systems or does one cover everything?

**Comment by seven3five** [comment]
Perhaps I screwed something up. I completely reinstalled the Device Handler and was forced to use the old SmartApp as nothing was showing as new. I have the MyQLite App showing in my SmartThing Classic but after I enter my credentials it just goes to a blank page. If I hit "Done" I get Error saving unnamed page. Please contact SmartApp developer. What am I missing?

**Comment by brbeaird** [comment]
> I noticed the one example of how to update using smartthings but what about the other systems or does one cover everything?

This is a SmartApp that integrates MyQ with SmartThings. If you haven't noticed anything wrong, my guess is you're not really using this with SmartThings but are relying more on the native MyQ app and Alexa to control your door. You're getting the e-mails because you're following this repository on github (look up at the top of this page, and you'll see an eyeball icon where you can choose to watch and receive notifications).

> was forced to use the old SmartApp as nothing was showing as new.

Something is definitely not right here. You'll need to install the newest version of everything (should show version 3.1.0 in the code). You may just need to manually copy/paste the code in.

**Comment by justintime** [comment]
I haven't had the time to troubleshoot just yet, but I wanted to report that I'm having trouble with the update, and specifically that I have Craftsman openers.  My app stopped working a few days back when everyone else's did.  I just went and did the update.  I will note that I switched from copy/paste code in the IDE to the github integration, but I don't think that's the problem.  

In the SmartApp, I'm able to log in, and it detects my Gateway Brand as Craftsman correctly.  However, under Connected Devices, it has the old device ID for my two openers.  When I click into Modify Devices per the instructions, it says:
```Could not find any supported device(s).  Please report to author about these devices: []```

When I get a little time later I'll dig in a bit more, just wanted to see if anyone else with Craftsman door openers has had success or failure with the upgrade.

**Comment by phaldor8** [comment]
@ Justin,

Sounds like you didn't hit the button to update the code from the
repository and you're still on the old code.  Without seeing your console,
my guess is you didn't update both the device handlers and the MyQ SmartApp
from within the SmartThings dashboard.  Another problem may be that your
devices are still referencing the old copy/paste device handlers instead of
the new ones updated from the github integration.


Christopher Goodrich B.S., CISSP, ISSEP, ISSMP, HCISPP
phaldor8@gmail.com
phaldor@comcast.net
505-227-6130

**Comment by justintime** [comment]
Nope, I'm on 3.1.0, I know I got things updated as it says so in the UI.

I actually found something that makes me think this is a bug in the new version with Craftsman.  I'm going to start a new issue for this.

**Comment by pup975** [comment]
I've updated everything to 3.1.0 and logged into MyQ account on the ST app. When I try to modify the devices, I get this error:

There was a problem updating devices: java.lang.NullPointerException: Cannot get property 'MyQDeviceID' on null object. 
Line number: unknown 
Last successful step: Door device creation.

My Gateway Brand is listed as Liftmaster on the MyQ account.

**Comment by pup975** [comment]
> I've updated everything to 3.1.0 and logged into MyQ account on the ST app. When I try to modify the devices, I get this error:
> 
> There was a problem updating devices: java.lang.NullPointerException: Cannot get property 'MyQDeviceID' on null object.
> Line number: unknown
> Last successful step: Door device creation.
> 
> My Gateway Brand is listed as Liftmaster on the MyQ account.

Nevermind. When I actually try to use it with SmartThings, the garage still closes and opens, so despite the error message, it's working.

**Comment by brbeaird** [comment]
> despite the error message, it's working.

Hopefully it was just a one-time glitch during the conversion. If the error messages continue, let me know.

**Comment by seven3five** [comment]
Got the new code published, went through the setup steps but was never asked what type of garage door I was using. Everything shows up but Garage Door shows "OPENING" and never actually opens or returns an error code. Suggestions?

**Comment by brbeaird** [comment]
Check live logging in the IDE when you try to refresh or open/close the
door. See what errors you get?

**Comment by montymc1** [comment]
Thanks for the app. Liked it so much, sent some money for it.
Worked over a year just fine. Just stopped.. I did a uninstall and reinstall.

This is my error

There was a problem updating devices:
org.springframework.security.access.AccessDeniedException:Access is denied
Line number: unknown
Last successful step: Sensor Indexing

Any Suggestions?

Thanks

**Comment by brbeaird** [comment]
Something is definitely weird with the install. You might try bringing the updated code over again and then stepping through the setup again.

**Comment by junklocken970** [comment]
Hi, jumping in late, here.  My Q Lite stopped working with Smartthings.  I have been trying to figure out the problem, and as of now, I cannot get logged in to the MyQ Lite SmartApp in Smartthings.  It repeatedly tells me after entering the Username and Password that "The username or password you entered is incorrect.  Go back and try again."  I have tried this multiple times to no avail.  I am using the username and password which I use to log in to the MyQ app.  I have updated the code of MyQ Lite to version 3.1.1 - as of today.  Any ideas why I cannot get logged in?

**Comment by phaldor8** [comment]
I can verify that this is an issue for me as well it just happened today or it least I just noticed it today it was working earlier this morning

Sincerely,

Christopher M Goodrich
phaldor8@gmail.com
(505) 227-6130

**Comment by phaldor8** [comment]
Actually cancel that it was not working for a very brief period of time and now it’s back up probably a small glitch on the MyQ site login server

Sincerely,

Christopher M Goodrich
phaldor8@gmail.com
(505) 227-6130

**Comment by ikonis** [comment]
I can verify that logins stopped working again today.
Uninstalled, and reinstalled... error on login... with correct U/P

**Comment by brbeaird** [comment]
MyQ was having issues across the board on 12/26. They got it fixed, though, so things should be back up and running.

**Comment by dinrajr** [comment]
I have setup everything per instructions.. the MyQ Lite app installed and configured correctly.. But I'm getting an error 'Can't connect to Device, check device and try again' when I hit Door opener/closer buttons.. thoughts?

**Comment by dinrajr** [comment]
I installed SmartThings Classic app and it worked to open the garage door. Although the close is not working.

**Comment by Memphis1931** [comment]
Ok, I know this is simple, but I haven’t updated any smart apps or device drivers for years and I can’t remember how I add this new MyQLite app and device drivers to my smartthings.  Also, how do I get this to update automatically in the future?  Thanks

**Comment by Memphis1931** [comment]
So I figured out how to add and publish and I even uninstalled and reinstalled the new myQ lite app but the garage still won’t open or close by pushing the smartthings app buttons... what am I missing here?

**Comment by DLThompson06** [comment]
This just happened to me today.  Everything was working fine and then I went to close my garage door through Alexa and got a push notification from Smartthings "Warning: MyQ command failed due to bad login."  Going into the MyQ Lite app in Smartthings (classic) showed that I wasn't logged in, so I tried multiple times, but it keeps saying "The username or password you entered is incorrect.  Go back and try again." even though the same username and password work fine in the Chamberlain MyQ app (outside of Smartthings).  Help?

**Comment by brbeaird** [comment]
SmartApp update was pushed to fix that. Update your code and you should be
good to go.

**Comment by DLThompson06** [comment]
When you say "Update your code" can you be more specific?  Sorry if it's obvious...

**Comment by junklocken970** [comment]
Same problem here
________________________________

**Comment by atlflyer** [comment]
In the SmartThings IDE, go to the My SmartApps page. Click "Update from repo" button. Choose SmartThings_MyQ (master) from the drop down. Click the check box by the smart app name, check "publish" at the bottom and then click "execute update". Go to the My Device Handlers tab and do the same thing (there will be multiple items you need to check this time.

If you don't see SmartThings_MyQ in the drop down, it means you cut and paste the code yourself instead of using the github integration. In this case, you'll need to grab the latest version from the repository and cut & paste replace the old code on the My SmartApps and My Device Handlers page for all of the MyQ items.

**Comment by DLThompson06** [comment]
Thank you for taking the time to explain it so clearly.  It's been a while since I set everything up, but I guess I must have cut and pasted everything.  The only thing that showed up in the dropdown for the SmartThings_MyQ SmartApps was in the Obsolete column, but I updated it anyway.  In the Device Handlers dropdown, there wasn't anything.  Guess I'll see if I can figure out where to find them!  Thanks again for your help.  I'll be back to update on my progress in case it helps anyone else.

**Comment by atlflyer** [comment]
This is the github repository for that project, so you're in the right place. You can find the code and setup instructions here: [https://github.com/brbeaird/SmartThings_MyQ](https://github.com/brbeaird/SmartThings_MyQ)

If you have any problems, it might be easiest to delete the smart app and any MyQ-related devices you find on your My Devices tab and start over.

**Comment by DLThompson06** [comment]
Yes, it ended up being easier to delete the smart app and reinstall it.  This time I used the community installer, so my guess is that it will let me know when an update is available and I can do it more easily next time?  Everything's working again, as it was before.  Thanks for your help!

**Comment by phardy13** [comment]
Does not work on my side :( deleted everything reinstalled everything in the new app. I can get in my credentials, see my door, create the virtual switch but then nothing can make my garage move (i do not have any sensor). Everythings work fine directly in the iOS myQ app though. What would you need to look into it?

**Comment by osborne1248** [comment]
Looks like this just happened again today.  When trying to log in through MyQ in SmartThings getting the "The username or password you entered is incorrect. Go back and try again."

 
@brbeaird - can you work your magic please sir?

**Comment by brbeaird** [comment]
Yep, MyQ changed something, and this is currently broken. I’m not sure at this point if it’s a permanent change - this has happened occasionally in the past where it comes back up the next day.

The good news is there is a newer version of the API login flow that some other integrations (HomeBridge, pymyq) are using successfully. The bad news is it is not a simple change to implement - a couple parts in particular I’m not really sure will work within Groovy. I will see what I can do, but it may be several days before I make any real progress.

**Comment by raccinf** [comment]
@brbeaird  Thanks for your work!

**Comment by JimMay3** [comment]
I been told the overall issue with this not being an official part of ST is not myQ/Chamberlian, it's that ST does not want to play by myQ's rules, thus they are not a white listed/trusted vendor.

**Comment by john022662** [comment]
This is still and issue on SmartThings and Hubitat. Any news?
